export const FETCH_CONVERSATIONS = "FETCH_CONVERSATIONS";
export const FETCH_CONVERSATIONS_RESULT = "FETCH_CONVERSATIONS_RESULT";
export const FETCH_CONVERSATIONS_ERROR = "FETCH_CONVERSATIONS_ERROR";

export const fetchConversations = () => ({
  type: FETCH_CONVERSATIONS
});
