export const CREATE_GAMING_SESSION = "CREATE_GAMING_SESSION";
export const CREATE_GAMING_SESSION_RESULT =
  "CREATE_GAMING_SESSION_ERROR_RESULT";
export const CREATE_GAMING_SESSION_ERROR = "CREATE_GAMING_SESSION_ERROR";

export const EDIT_GAMING_SESSION = "EDIT_GAMING_SESSION";
export const EDIT_GAMING_SESSION_RESULT = "EDIT_GAMING_SESSION_RESULT";
export const EDIT_GAMING_SESSION_ERROR = "EDIT_GAMING_SESSION_ERROR";

export const DELETE_GAMING_SESSION = "DELETE_GAMING_SESSION";
export const DELETE_GAMING_SESSION_RESULT = "DELETE_GAMING_SESSION_RESULT";
export const DELETE_GAMING_SESSION_ERROR = "DELETE_GAMING_SESSION_ERROR";

export const FETCH_GAMING_SESSION = "FETCH_GAMING_SESSION";
export const FETCH_GAMING_SESSION_RESULT = "FETCH_GAMING_SESSION_RESULT";
export const FETCH_GAMING_SESSION_ERROR = "FETCH_GAMING_SESSION_ERROR";

export const FETCH_GAMING_SESSIONS = "FETCH_GAMING_SESSIONS";
export const FETCH_GAMING_SESSIONS_RESULT = "FETCH_GAMING_SESSIONS_RESULT";
export const FETCH_GAMING_SESSIONS_ERROR = "FETCH_GAMING_SESSIONS_ERROR";
export const FETCH_GAMING_SESSIONS_NO_DATA = "FETCH_GAMING_SESSIONS_NO_DATA";
export const FETCH_GAMING_SESSIONS_NO_SEARCH_RESULTS =
  "FETCH_GAMING_SESSIONS_NO_SEARCH_RESULTS";

export const REFRESH_GAMING_SESSIONS = "REFRESH_GAMING_SESSIONS";
export const LOAD_MORE_GAMING_SESSIONS = "LOAD_MORE_GAMING_SESSIONS";
export const LOAD_MORE_GAMING_SESSIONS_RESULT =
  "LOAD_MORE_GAMING_SESSIONS_RESULT";

export const FETCH_MY_GAMING_SESSIONS = "FETCH_MY_GAMING_SESSIONS";
export const FETCH_MY_GAMING_SESSIONS_RESULT =
  "FETCH_MY_GAMING_SESSIONS_RESULT";
export const FETCH_MY_GAMING_SESSIONS_ERROR = "FETCH_MY_GAMING_SESSIONS_ERROR";
export const FETCH_MY_GAMING_SESSIONS_NO_DATA =
  "FETCH_MY_GAMING_SESSIONS_NO_DATA";
export const CLEAR_MY_GAMING_SESSIONS = "ClEAR_MY_GAMING_SESSIONS";
export const REFRESH_MY_GAMING_SESSIONS = "REFRESH_MY_GAMING_SESSIONS";
export const LOAD_MORE_MY_GAMING_SESSIONS = "LOAD_MORE_MY_GAMING_SESSIONS";
export const LOAD_MORE_MY_GAMING_SESSIONS_RESULT =
  "LOAD_MORE_MY_GAMING_SESSIONS_RESULT";

export const FETCH_GROUP_GAMING_SESSIONS = "FETCH_GROUP_GAMING_SESSIONS";
export const FETCH_GROUP_GAMING_SESSIONS_RESULT =
  "FETCH_GROUP_GAMING_SESSIONS_RESULT";
export const FETCH_GROUP_GAMING_SESSIONS_ERROR =
  "FETCH_GROUP_GAMING_SESSIONS_ERROR";
export const FETCH_GROUP_GAMING_SESSIONS_NO_DATA =
  "FETCH_GROUP_GAMING_SESSIONS_NO_DATA";
export const CLEAR_GROUP_GAMING_SESSIONS = "CLEAR_GROUP_GAMING_SESSIONS";
export const REFRESH_GROUP_GAMING_SESSIONS = "REFRESH_GROUP_GAMING_SESSIONS";
export const LOAD_MORE_GROUP_GAMING_SESSIONS =
  "LOAD_MORE_GROUP_GAMING_SESSIONS";
export const LOAD_MORE_GROUP_GAMING_SESSIONS_RESULT =
  "LOAD_MORE_GROUP_GAMING_SESSIONS_RESULT";

export const FETCH_RECENT_GAMING_SESSIONS = "FETCH_RECENT_GAMING_SESSIONS";
export const FETCH_RECENT_GAMING_SESSIONS_RESULT =
  "FETCH_RECENT_GAMING_SESSIONS_RESULT";
export const FETCH_RECENT_GAMING_SESSIONS_ERROR =
  "FETCH_RECENT_GAMING_SESSIONS_ERROR";
export const FETCH_RECENT_GAMING_SESSIONS_NO_DATA =
  "FETCH_RECENT_GAMING_SESSIONS_NO_DATA";
export const CLEAR_RECENT_GAMING_SESSIONS = "CLEAR_RECENT_GAMING_SESSIONS";
export const REFRESH_RECENT_GAMING_SESSIONS = "REFRESH_RECENT_GAMING_SESSIONS";
export const LOAD_MORE_RECENT_GAMING_SESSIONS =
  "LOAD_MORE_RECENT_GAMING_SESSIONS";
export const LOAD_MORE_RECENT_GAMING_SESSIONS_RESULT =
  "LOAD_MORE_RECENT_GAMING_SESSIONS_RESULT";

export const FETCH_PROFILE_GAMING_SESSIONS = "FETCH_PROFILE_GAMING_SESSIONS";
export const FETCH_PROFILE_GAMING_SESSIONS_RESULT =
  "FETCH_PROFILE_GAMING_SESSIONS_RESULT";
export const FETCH_PROFILE_GAMING_SESSIONS_ERROR =
  "FETCH_PROFILE_GAMING_SESSIONS_ERROR";
export const FETCH_PROFILE_GAMING_SESSIONS_NO_DATA =
  "FETCH_PROFILE_GAMING_SESSIONS_NO_DATA";

export const createGamingSession = gamingSession => ({
  type: CREATE_GAMING_SESSION,
  gamingSession
});

export const editGamingSession = gamingSession => ({
  type: EDIT_GAMING_SESSION,
  gamingSession
});

export const deleteGamingSession = deleteGamingSessionId => ({
  type: DELETE_GAMING_SESSION,
  deleteGamingSessionId
});

export const fetchGamingSession = gamingSessionId => ({
  type: FETCH_GAMING_SESSION,
  gamingSessionId
});

export const fetchGamingSessions = endpoint => ({
  type: FETCH_GAMING_SESSIONS,
  endpoint
});

export const refreshGamingSessions = endpoint => ({
  type: REFRESH_GAMING_SESSIONS,
  endpoint
});

export const loadMoreGamingSessions = endpoint => ({
  type: LOAD_MORE_GAMING_SESSIONS,
  endpoint
});

export const fetchMyGamingSessions = endpoint => ({
  type: FETCH_MY_GAMING_SESSIONS,
  endpoint
});

export const refreshMyGamingSessions = endpoint => ({
  type: REFRESH_MY_GAMING_SESSIONS,
  endpoint
});

export const loadMoreMyGamingSessions = endpoint => ({
  type: LOAD_MORE_MY_GAMING_SESSIONS,
  endpoint
});

export const fetchGroupGamingSessions = endpoint => ({
  type: FETCH_GROUP_GAMING_SESSIONS,
  endpoint
});

export const refreshGroupGamingSessions = endpoint => ({
  type: REFRESH_GROUP_GAMING_SESSIONS,
  endpoint
});

export const loadMoreGroupGamingSessions = endpoint => ({
  type: LOAD_MORE_GROUP_GAMING_SESSIONS,
  endpoint
});

export const fetchRecentGamingSessions = endpoint => ({
  type: FETCH_RECENT_GAMING_SESSIONS,
  endpoint
});

export const refreshRecentGamingSessions = endpoint => ({
  type: REFRESH_RECENT_GAMING_SESSIONS,
  endpoint
});

export const loadMoreRecentGamingSessions = endpoint => ({
  type: LOAD_MORE_RECENT_GAMING_SESSIONS,
  endpoint
});

export const fetchProfileGamingSessions = () => ({
  type: FETCH_PROFILE_GAMING_SESSIONS
});
