export const FETCH_NOTIFICATIONS = "FETCH_NOTIFICATIONS";
export const FETCH_NOTIFICATIONS_RESULT = "FETCH_NOTIFICATIONS_RESULT";
export const FETCH_NOTIFICATIONS_ERROR = "FETCH_NOTIFICATIONS_ERROR";
export const FETCH_NOTIFICATIONS_NO_DATA = "FETCH_NOTIFICATIONS_NO_DATA";

export const fetchNotifications = () => ({
  type: FETCH_NOTIFICATIONS
});
